#*****************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# generate_vivado.tcl: Tcl script for re-creating project 'vivado_project'
#
# Generated by Vivado on Sun Nov 29 21:21:06 -0500 2020
# IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (generate_vivado.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/red_coe/red_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/blue_coe/blue_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/green_coe/green_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chop_up_coe/chop_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chop_down_coe/chop_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chop_right_coe/chop_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chop_left_coe/chop_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_up_coe/chopped_onion_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_down_coe/chopped_onion_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_right_coe/chopped_onion_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_left_coe/chopped_onion_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_up_coe/empty_bowl_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_down_coe/empty_bowl_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_right_coe/empty_bowl_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_left_coe/empty_bowl_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_up_coe/empty_pot_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_down_coe/empty_pot_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_right_coe/empty_pot_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_left_coe/empty_pot_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_up_coe/extinguisher_off_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_down_coe/extinguisher_off_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_right_coe/extinguisher_off_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_left_coe/extinguisher_off_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_up_coe/extinguisher_on_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_down_coe/extinguisher_on_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_right_coe/extinguisher_on_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_left_coe/extinguisher_on_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_up_coe/full_bowl_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_down_coe/full_bowl_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_right_coe/full_bowl_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_left_coe/full_bowl_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/move_up_coe/move_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/move_down_coe/move_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/move_right_coe/move_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/move_left_coe/move_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_up_coe/soup_pot_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_down_coe/soup_pot_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_right_coe/soup_pot_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_left_coe/soup_pot_left_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_up_coe/whole_onion_up_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_down_coe/whole_onion_down_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_right_coe/whole_onion_right_coe.xci"
#    "c:/Users/lacth/overcooked-fpga/fpga/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_left_coe/whole_onion_left_coe.xci"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/lacth/overcooked-fpga/fpga/clk_25mhz.v"
#    "C:/Users/lacth/overcooked-fpga/fpga/action.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/check_in_front.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/game_logic.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/graphics.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/grid_in_front.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/main_FPGA_control.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/network.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/orders_and_points.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/p_state.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/pixel_to_grid.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/player_blob.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/player_move.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/table_counters.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/time_remaining.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/xvga_starter.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/top_level.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/grid_to_pixel.sv"
#    "C:/Users/lacth/overcooked-fpga/fpga/serial.sv"
#    "c:/Users/lacth/overcooked-fpga/sprites/red.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/blue.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/green.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chop/chop_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chop/chop_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chop/chop_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chop/chop_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chopped_onion/chopped_onion_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chopped_onion/chopped_onion_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chopped_onion/chopped_onion_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/chopped_onion/chopped_onion_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_bowl/empty_bowl_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_bowl/empty_bowl_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_bowl/empty_bowl_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_bowl/empty_bowl_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_pot/empty_pot_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_pot/empty_pot_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_pot/empty_pot_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/empty_pot/empty_pot_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_off/extinguisher_off_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_off/extinguisher_off_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_off/extinguisher_off_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_off/extinguisher_off_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_on/extinguisher_on_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_on/extinguisher_on_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_on/extinguisher_on_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/extinguisher_on/extinguisher_on_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/full_bowl/full_bowl_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/full_bowl/full_bowl_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/full_bowl/full_bowl_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/full_bowl/full_bowl_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/move/move_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/move/move_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/move/move_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/move/move_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/soup_pot/soup_pot_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/soup_pot/soup_pot_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/soup_pot/soup_pot_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/soup_pot/soup_pot_left.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/whole_onion/whole_onion_up.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/whole_onion/whole_onion_down.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/whole_onion/whole_onion_right.coe"
#    "c:/Users/lacth/overcooked-fpga/sprites/whole_onion/whole_onion_left.coe"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "vivado_project"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "generate_vivado.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/vivado_project"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:nexys4_ddr:part0:1.1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "nexys4_ddr" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "82" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "82" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "82" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "82" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "82" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "82" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "44" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "82" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "55" -objects $obj
set_property -name "xpm_libraries" -value "XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/clk_25mhz.v"] \
 [file normalize "${origin_dir}/action.sv"] \
 [file normalize "${origin_dir}/check_in_front.sv"] \
 [file normalize "${origin_dir}/game_logic.sv"] \
 [file normalize "${origin_dir}/graphics.sv"] \
 [file normalize "${origin_dir}/grid_in_front.sv"] \
 [file normalize "${origin_dir}/main_FPGA_control.sv"] \
 [file normalize "${origin_dir}/network.sv"] \
 [file normalize "${origin_dir}/orders_and_points.sv"] \
 [file normalize "${origin_dir}/p_state.sv"] \
 [file normalize "${origin_dir}/pixel_to_grid.sv"] \
 [file normalize "${origin_dir}/player_blob.sv"] \
 [file normalize "${origin_dir}/player_move.sv"] \
 [file normalize "${origin_dir}/table_counters.sv"] \
 [file normalize "${origin_dir}/time_remaining.sv"] \
 [file normalize "${origin_dir}/xvga_starter.sv"] \
 [file normalize "${origin_dir}/top_level.sv"] \
 [file normalize "${origin_dir}/grid_to_pixel.sv"] \
 [file normalize "${origin_dir}/serial.sv"] \
 [file normalize "${origin_dir}/../sprites/red.coe"] \
 [file normalize "${origin_dir}/../sprites/blue.coe"] \
 [file normalize "${origin_dir}/../sprites/green.coe"] \
 [file normalize "${origin_dir}/../sprites/chop/chop_up.coe"] \
 [file normalize "${origin_dir}/../sprites/chop/chop_down.coe"] \
 [file normalize "${origin_dir}/../sprites/chop/chop_right.coe"] \
 [file normalize "${origin_dir}/../sprites/chop/chop_left.coe"] \
 [file normalize "${origin_dir}/../sprites/chopped_onion/chopped_onion_up.coe"] \
 [file normalize "${origin_dir}/../sprites/chopped_onion/chopped_onion_down.coe"] \
 [file normalize "${origin_dir}/../sprites/chopped_onion/chopped_onion_right.coe"] \
 [file normalize "${origin_dir}/../sprites/chopped_onion/chopped_onion_left.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_bowl/empty_bowl_up.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_bowl/empty_bowl_down.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_bowl/empty_bowl_right.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_bowl/empty_bowl_left.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_pot/empty_pot_up.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_pot/empty_pot_down.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_pot/empty_pot_right.coe"] \
 [file normalize "${origin_dir}/../sprites/empty_pot/empty_pot_left.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_off/extinguisher_off_up.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_off/extinguisher_off_down.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_off/extinguisher_off_right.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_off/extinguisher_off_left.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_on/extinguisher_on_up.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_on/extinguisher_on_down.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_on/extinguisher_on_right.coe"] \
 [file normalize "${origin_dir}/../sprites/extinguisher_on/extinguisher_on_left.coe"] \
 [file normalize "${origin_dir}/../sprites/full_bowl/full_bowl_up.coe"] \
 [file normalize "${origin_dir}/../sprites/full_bowl/full_bowl_down.coe"] \
 [file normalize "${origin_dir}/../sprites/full_bowl/full_bowl_right.coe"] \
 [file normalize "${origin_dir}/../sprites/full_bowl/full_bowl_left.coe"] \
 [file normalize "${origin_dir}/../sprites/move/move_up.coe"] \
 [file normalize "${origin_dir}/../sprites/move/move_down.coe"] \
 [file normalize "${origin_dir}/../sprites/move/move_right.coe"] \
 [file normalize "${origin_dir}/../sprites/move/move_left.coe"] \
 [file normalize "${origin_dir}/../sprites/soup_pot/soup_pot_up.coe"] \
 [file normalize "${origin_dir}/../sprites/soup_pot/soup_pot_down.coe"] \
 [file normalize "${origin_dir}/../sprites/soup_pot/soup_pot_right.coe"] \
 [file normalize "${origin_dir}/../sprites/soup_pot/soup_pot_left.coe"] \
 [file normalize "${origin_dir}/../sprites/whole_onion/whole_onion_up.coe"] \
 [file normalize "${origin_dir}/../sprites/whole_onion/whole_onion_down.coe"] \
 [file normalize "${origin_dir}/../sprites/whole_onion/whole_onion_right.coe"] \
 [file normalize "${origin_dir}/../sprites/whole_onion/whole_onion_left.coe"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/action.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/check_in_front.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/game_logic.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/graphics.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/grid_in_front.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/main_FPGA_control.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/network.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/orders_and_points.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/p_state.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/pixel_to_grid.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/player_blob.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/player_move.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/table_counters.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/time_remaining.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/xvga_starter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/top_level.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/grid_to_pixel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/serial.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "top_level" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/red_coe/red_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "red_coe/red_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/blue_coe/blue_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "blue_coe/blue_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/green_coe/green_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "green_coe/green_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chop_up_coe/chop_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chop_up_coe/chop_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chop_down_coe/chop_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chop_down_coe/chop_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chop_right_coe/chop_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chop_right_coe/chop_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chop_left_coe/chop_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chop_left_coe/chop_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_up_coe/chopped_onion_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chopped_onion_up_coe/chopped_onion_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_down_coe/chopped_onion_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chopped_onion_down_coe/chopped_onion_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_right_coe/chopped_onion_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chopped_onion_right_coe/chopped_onion_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/chopped_onion_left_coe/chopped_onion_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "chopped_onion_left_coe/chopped_onion_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_up_coe/empty_bowl_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_bowl_up_coe/empty_bowl_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_down_coe/empty_bowl_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_bowl_down_coe/empty_bowl_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_right_coe/empty_bowl_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_bowl_right_coe/empty_bowl_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_bowl_left_coe/empty_bowl_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_bowl_left_coe/empty_bowl_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_up_coe/empty_pot_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_pot_up_coe/empty_pot_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_down_coe/empty_pot_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_pot_down_coe/empty_pot_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_right_coe/empty_pot_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_pot_right_coe/empty_pot_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/empty_pot_left_coe/empty_pot_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "empty_pot_left_coe/empty_pot_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_up_coe/extinguisher_off_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_off_up_coe/extinguisher_off_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_down_coe/extinguisher_off_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_off_down_coe/extinguisher_off_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_right_coe/extinguisher_off_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_off_right_coe/extinguisher_off_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_off_left_coe/extinguisher_off_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_off_left_coe/extinguisher_off_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_up_coe/extinguisher_on_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_on_up_coe/extinguisher_on_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_down_coe/extinguisher_on_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_on_down_coe/extinguisher_on_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_right_coe/extinguisher_on_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_on_right_coe/extinguisher_on_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/extinguisher_on_left_coe/extinguisher_on_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "extinguisher_on_left_coe/extinguisher_on_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_up_coe/full_bowl_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "full_bowl_up_coe/full_bowl_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_down_coe/full_bowl_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "full_bowl_down_coe/full_bowl_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_right_coe/full_bowl_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "full_bowl_right_coe/full_bowl_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/full_bowl_left_coe/full_bowl_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "full_bowl_left_coe/full_bowl_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/move_up_coe/move_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "move_up_coe/move_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/move_down_coe/move_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "move_down_coe/move_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/move_right_coe/move_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "move_right_coe/move_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/move_left_coe/move_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "move_left_coe/move_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_up_coe/soup_pot_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "soup_pot_up_coe/soup_pot_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_down_coe/soup_pot_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "soup_pot_down_coe/soup_pot_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_right_coe/soup_pot_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "soup_pot_right_coe/soup_pot_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/soup_pot_left_coe/soup_pot_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "soup_pot_left_coe/soup_pot_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_up_coe/whole_onion_up_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "whole_onion_up_coe/whole_onion_up_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_down_coe/whole_onion_down_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "whole_onion_down_coe/whole_onion_down_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_right_coe/whole_onion_right_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "whole_onion_right_coe/whole_onion_right_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/vivado_project.srcs/sources_1/ip/whole_onion_left_coe/whole_onion_left_coe.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "whole_onion_left_coe/whole_onion_left_coe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "top_level" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
